from pathlib import Path
import json
from html import escape
root = Path(__file__).resolve().parent
variants = json.loads((root/'h-colors/prompts.json').read_text())['variants']
options = [('H', 'Original white', 'Current H, unchanged.', 'refinements/classic-box-family-centered.png', '#ffffff')]
options += [(f'H{i+1}', v['name'], v['description'], v['output'], v['color']) for i,v in enumerate(variants, 1)]
cards = ''
for label,name,description,src,color in options:
    sizes = ''.join(f'<span><img src="{src}" alt="" width="{n}" height="{n}"><small>{n}</small></span>' for n in [16,24,32,48,64])
    cards += f'<article><a class="art" href="{src}" target="_blank"><img src="{src}" alt="{escape(name)} face on H"></a><div class="copy"><small>{label}</small><h2>{name}</h2><p>{description}</p><div class="swatch"><i style="background:{color}"></i><code>{color.upper()}</code><small>target</small></div></div><div class="sizes">{sizes}</div></article>'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BoxHaven · H face colors</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f6f1;color:#233f36;font:15px/1.5 -apple-system,BlinkMacSystemFont,sans-serif}main{max-width:1440px;margin:auto;padding:32px 24px}a{color:#36745b;text-underline-offset:4px}h1{font-size:40px;letter-spacing:-.04em;line-height:1.1;margin:24px 0 12px}p{color:#627169;margin:0}header{margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}article{min-width:0;border:1px solid #d7ddd2;border-radius:12px;overflow:hidden;background:#fbfaf6;display:flex;flex-direction:column}.art{display:block;aspect-ratio:1}.art img{display:block;width:100%;height:100%;object-fit:contain}.copy{padding:18px;flex:1}.copy small{color:#718377}h2{font-size:20px;letter-spacing:-.02em;margin:4px 0 8px}.copy p{font-size:14px;min-height:44px}.swatch{display:flex;align-items:center;gap:8px;margin-top:16px;font-size:12px}.swatch i{display:block;width:16px;height:16px;border:1px solid #cbd3c8;border-radius:50%}.sizes{display:flex;align-items:end;justify-content:center;gap:14px;padding:20px 8px;border-top:1px solid #d7ddd2;background:#f7f6f1}.sizes span{display:flex;flex-direction:column;align-items:center;gap:8px}.sizes small{font-size:10px;color:#627169}footer{margin-top:32px;border-top:1px solid #d7ddd2;padding-top:20px;color:#627169;font-size:12px}footer p{margin-bottom:8px}@media(max-width:1150px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.grid{grid-template-columns:1fr}main{padding:24px 18px}h1{font-size:32px}.copy p{min-height:0}}
</style><main><header><a href="refinements.html">← Shape & depth studies</a><h1>A softer face for H.</h1><p>Original white, warm cream, pale sage, and muted sage.</p></header><section class="grid">CARDS</section><footer><p>Imagegen color studies on paper. Swatches show requested color targets; generated colors may vary slightly. Small previews use 16, 24, 32, 48, and 64px canvases.</p><a href="h-colors/prompts.json">Prompts & saved image paths ↗</a></footer></main></html>'''
(root/'h-colors.html').write_text(page.replace('CARDS',cards))
