import { _electron as electron, expect } from 'playwright/test';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, chmodSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const temp = mkdtempSync(join(tmpdir(), 'boxhaven-desktop-smoke-'));
const stateFile = join(temp, 'boxes.json');
const out = join(root, '.artifacts'); mkdirSync(out, { recursive: true });
const fixture = join(root, 'test/fixture-cli.cjs'); chmodSync(fixture, 0o755);
const machine = (name, status, ready = true) => ({ name, status, bootstrap_complete: ready, team_slug: 'Personal', provider: 'digitalocean', region: 'nyc3', size: 'small' });
let state = { machines: [machine('api-cleanup', 'online'), machine('dashboard-redesign', 'online'), machine('docs-refresh', 'creating', false), machine('nightly-tests', 'offline')] };
const save = () => writeFileSync(stateFile, JSON.stringify(state)); save();
let app;
try {
  app = await electron.launch({ args: [join(root, 'test/fixture-main.cjs')], env: { ...process.env, TEST_BH_CLI: fixture, TEST_USER_DATA: join(temp, 'profile'), TEST_BH_STATE: stateFile } });
  let page = await app.firstWindow();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await expect(page.locator('.box-row')).toHaveCount(4);
  await page.screenshot({ path: join(out, 'desktop-boxes.png') });
  await page.getByRole('button', { name: 'api-cleanup, online', exact: true }).click();
  let terminal = page.locator('.terminal-pane:not([hidden])');
  await expect(terminal).toContainText('Desktop PTY fixture');
  await page.keyboard.type('first-session-marker'); await page.keyboard.press('Enter');
  await expect(terminal).toContainText('Received: first-session-marker');
  await page.getByRole('button', { name: 'dashboard-redesign, online', exact: true }).click();
  await expect(terminal).toContainText('dashboard-redesign');
  await page.getByRole('button', { name: 'api-cleanup, online', exact: true }).click();
  await expect(terminal).toContainText('Received: first-session-marker');
  assert.equal(readFileSync(`${stateFile}.connections`, 'utf8').trim().split('\n').length, 2, 'switching boxes must reuse the PTY');
  await page.getByRole('button', { name: 'Connection settings' }).click();
  await page.getByRole('button', { name: 'Sign in with your browser' }).click();
  await expect(page.locator('#login-status')).toContainText('Detach your open sessions');
  await page.getByRole('button', { name: 'Close settings' }).click();
  await assert.rejects(page.evaluate(() => window.boxhaven.connect('--help', 80, 24)), /not ready/);
  await page.screenshot({ path: join(out, 'desktop-terminal.png') });
  await page.getByRole('button', { name: 'Detach', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reconnect', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
  await expect(page.locator('#connection-state')).toHaveText('Terminal open');
  await page.getByRole('button', { name: 'docs-refresh, creating', exact: true }).click();
  await expect(page.locator('#welcome-title')).toHaveText('Your box is getting ready.');
  await expect(page.locator('#terminals')).toBeHidden();
  await page.getByRole('searchbox').fill('dashboard');
  await expect(page.locator('.box-row')).toHaveCount(1);
  await page.getByRole('searchbox').fill('');
  state.machines[2] = machine('docs-refresh', 'online'); save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(terminal).toContainText('docs-refresh');
  // Exercise real native PTY resizing, not just the page layout.
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(820, 540));
  await expect(terminal).toContainText('SIZE:');
  assert.equal(await terminal.evaluate(element => {
    const screen = element.querySelector('.xterm-screen').getBoundingClientRect();
    const pane = element.getBoundingClientRect();
    return screen.right <= pane.right + 1 && screen.bottom <= pane.bottom + 1;
  }), true, 'terminal cells must fit inside the visible pane');
  await page.screenshot({ path: join(out, 'desktop-small.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  const reopened = app.waitForEvent('window');
  await app.evaluate(async ({ app, BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows()[0];
    await new Promise(resolve => { window.once('closed', resolve); window.close(); });
    app.emit('activate');
  });
  page = await reopened;
  page.on('pageerror', error => errors.push(error.message));
  terminal = page.locator('.terminal-pane:not([hidden])');
  await expect(terminal).toContainText('docs-refresh');
  await expect(page.locator('#connection-state')).toHaveText('Terminal open');
  state.error = 'Could not reach the backend. Please try again.'; save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Could not reach');
  await expect(page.locator('.box-row')).toHaveCount(4);
  await page.screenshot({ path: join(out, 'desktop-error.png') });
  delete state.error; state.machines = []; save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(page.locator('.box-row')).toHaveCount(0);
  await expect(page.locator('#empty-guide')).toBeVisible();
  await page.screenshot({ path: join(out, 'desktop-empty.png') });
  await page.getByRole('button', { name: 'Connection settings' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({ path: join(out, 'desktop-settings.png') });
  assert.deepEqual(errors, []);
  console.log('Desktop smoke passed: native PTY input/output, switching, reconnect, readiness, resize, refresh errors, empty state, settings.');
} finally { if (app) await app.close(); rmSync(temp, { recursive: true, force: true }); }
