import { _electron as electron, expect } from 'playwright/test';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, chmodSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const temp = mkdtempSync(join(tmpdir(), 'boxhaven-desktop-smoke-'));
const stateFile = join(temp, 'boxes.json');
const out = join(root, '.artifacts'); mkdirSync(out, { recursive: true });
const fixture = join(root, 'test/fixture-cli.cjs'); chmodSync(fixture, 0o755);
const machine = (name, status, ready = true) => ({ name, status, provider_id: name, preview_url: name === 'api-cleanup' ? 'https://api-cleanup.example.com/' : '', bootstrap_complete: ready, team_slug: 'Personal', provider: 'digitalocean', region: 'nyc3', size: 'small' });
let state = { machines: [machine('api-cleanup', 'online'), machine('dashboard-redesign', 'online'), machine('docs-refresh', 'creating', false), machine('nightly-tests', 'offline')] };
const save = () => writeFileSync(stateFile, JSON.stringify(state)); save();
let app;
try {
  app = await electron.launch({ args: [join(root, 'test/fixture-main.cjs')], env: { ...process.env, TEST_BH_CLI: fixture, TEST_USER_DATA: join(temp, 'profile'), TEST_BH_STATE: stateFile } });
  // Stub only the OS boundary; exercise the real IPC, validation and CLI paths.
  await app.evaluate(({ shell, dialog }) => {
    global.desktopSmoke = { opened: [], confirmations: [], response: 0 };
    shell.openExternal = async url => {
      if (global.desktopSmoke.openError) throw new Error('Browser could not be opened.');
      global.desktopSmoke.opened.push(url);
    };
    dialog.showMessageBox = async (_owner, options) => {
      global.desktopSmoke.confirmations.push(options);
      return { response: global.desktopSmoke.response };
    };
  });
  let page = await app.firstWindow();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await expect(page.locator('.box-row')).toHaveCount(4);
  await page.screenshot({ path: join(out, 'desktop-boxes.png') });
  await page.getByRole('button', { name: 'api-cleanup, online', exact: true }).click();
  let terminal = page.locator('.terminal-pane:not([hidden])');
  await expect(terminal).toContainText('Desktop PTY fixture');
  await page.getByRole('button', { name: 'Open preview' }).click();
  assert.deepEqual(await app.evaluate(() => global.desktopSmoke.opened), ['https://api-cleanup.example.com/']);
  await assert.rejects(page.evaluate(() => window.boxhaven.openPreview('https://attacker.example')), /no web preview/);
  await app.evaluate(() => { global.desktopSmoke.openError = true; });
  await page.getByRole('button', { name: 'Open preview' }).click();
  await expect(page.locator('#action-error')).toContainText('Browser could not be opened');
  await app.evaluate(() => { global.desktopSmoke.openError = false; });
  await terminal.locator('textarea').focus();
  await page.keyboard.type('first-session-marker'); await page.keyboard.press('Enter');
  await expect(terminal).toContainText('Received: first-session-marker');
  await page.getByRole('button', { name: 'dashboard-redesign, online', exact: true }).click();
  await expect(terminal).toContainText('dashboard-redesign');
  await expect(page.getByRole('button', { name: 'Open preview' })).toBeDisabled();
  await page.getByRole('button', { name: 'api-cleanup, online', exact: true }).click();
  await expect(terminal).toContainText('Received: first-session-marker');
  assert.equal(readFileSync(`${stateFile}.connections`, 'utf8').trim().split('\n').length, 2, 'switching boxes must reuse the PTY');
  await page.getByRole('button', { name: 'Connection settings' }).click();
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.locator('#login-status')).toContainText('Detach your open sessions');
  await page.getByRole('button', { name: 'Close settings' }).click();
  await assert.rejects(page.evaluate(() => window.boxhaven.connect('--help', 80, 24)), /not ready/);
  await page.screenshot({ path: join(out, 'desktop-terminal.png') });
  await page.getByRole('button', { name: 'Detach', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Reconnect', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
  await expect(page.locator('#connection-state')).toHaveText('Terminal open');
  await page.getByRole('button', { name: 'docs-refresh, creating', exact: true }).click();
  await expect(page.locator('#welcome-title')).toHaveText('Creating…');
  await expect(page.locator('#terminals')).toBeHidden();
  await page.getByRole('searchbox').fill('dashboard');
  await expect(page.locator('.box-row')).toHaveCount(1);
  await page.getByRole('searchbox').fill('');
  state.machines[2] = machine('docs-refresh', 'online'); save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(terminal).toContainText('docs-refresh');
  // Exercise real native PTY resizing, not just the page layout.
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(820, 540));
  await expect(terminal).toContainText('SIZE:');
  assert.equal(await terminal.evaluate(element => {
    const screen = element.querySelector('.xterm-screen').getBoundingClientRect();
    const pane = element.getBoundingClientRect();
    return screen.right <= pane.right + 1 && screen.bottom <= pane.bottom + 1;
  }), true, 'terminal cells must fit inside the visible pane');
  await page.screenshot({ path: join(out, 'desktop-small.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  const reopened = app.waitForEvent('window');
  await app.evaluate(async ({ app, BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows()[0];
    await new Promise(resolve => { window.once('closed', resolve); window.close(); });
    app.emit('activate');
  });
  page = await reopened;
  page.on('pageerror', error => errors.push(error.message));
  terminal = page.locator('.terminal-pane:not([hidden])');
  await expect(terminal).toContainText('docs-refresh');
  await expect(page.locator('#connection-state')).toHaveText('Terminal open');
  state.error = 'Could not reach the backend. Please try again.'; save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Could not reach');
  await expect(page.locator('.box-row')).toHaveCount(4);
  await page.screenshot({ path: join(out, 'desktop-error.png') });
  delete state.error; state.machines = []; save();
  await page.getByRole('button', { name: 'Refresh boxes', exact: true }).click();
  await expect(page.locator('.box-row')).toHaveCount(0);
  await expect(page.locator('#empty-guide')).toBeVisible();
  await page.screenshot({ path: join(out, 'desktop-empty.png') });
  await page.getByRole('button', { name: 'Connection settings' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({ path: join(out, 'desktop-settings.png') });
  await page.getByRole('button', { name: 'Close settings' }).click();
  await assert.rejects(page.evaluate(() => window.boxhaven.create('--help')), /lowercase/);
  await assert.rejects(page.evaluate(() => window.boxhaven.create('x'.repeat(64))), /63/);
  await page.locator('#create-first-box').click();
  await page.getByLabel('Box name', { exact: true }).fill('my-next-idea');
  await page.screenshot({ path: join(out, 'desktop-new-box.png') });
  await page.locator('#create-box').click();
  await expect(page.locator('#create-dialog')).not.toBeVisible();
  await expect(terminal).toContainText('boxhaven@my-next-idea');
  assert.deepEqual(JSON.parse(readFileSync(`${stateFile}.creations`, 'utf8').trim()).args, ['create', 'my-next-idea', '--no-sync']);
  await page.getByRole('button', { name: 'New box', exact: true }).click();
  await page.getByLabel('Box name', { exact: true }).fill('my-next-idea');
  await page.locator('#create-box').click();
  await expect(page.locator('#create-status')).toContainText('already exists');
  assert.equal(readFileSync(`${stateFile}.creations`, 'utf8').trim().split('\n').length, 1, 'duplicate must not invoke create');
  state = JSON.parse(readFileSync(stateFile, 'utf8'));
  state.createError = 'Provider quota exceeded.'; save();
  await page.getByLabel('Box name', { exact: true }).fill('quota-test');
  await page.locator('#create-box').click();
  await expect(page.locator('#create-status')).toContainText('Provider quota exceeded');
  await expect(page.locator('#create-box')).toBeEnabled();
  await expect(page.getByLabel('Box name', { exact: true })).toHaveValue('quota-test');
  await page.screenshot({ path: join(out, 'desktop-create-error.png') });
  delete state.createError; state.createDelay = 5000; save();
  await page.getByLabel('Box name', { exact: true }).fill('background-box');
  await page.locator('#create-box').click();
  await expect(page.locator('#create-box')).toBeDisabled();
  await assert.rejects(page.evaluate(() => window.boxhaven.create('second-box')), /already being created/);
  await assert.rejects(page.evaluate(() => window.boxhaven.login('https://example.com')), /finish before changing accounts/);
  await page.screenshot({ path: join(out, 'desktop-creating.png') });
  // Provisioning belongs to the app, not the lifetime of a renderer/window.
  const creatingWindow = app.waitForEvent('window');
  await app.evaluate(async ({ app, BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows()[0];
    await new Promise(resolve => { window.once('closed', resolve); window.close(); });
    app.emit('activate');
  });
  page = await creatingWindow;
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.locator('#creation-notice')).toContainText('Creating background-box');
  await page.getByRole('button', { name: 'New box', exact: true }).click();
  await expect(page.getByLabel('Box name', { exact: true })).toHaveValue('background-box');
  await expect(page.locator('#create-box')).toBeDisabled();
  await expect(page.locator('#create-dialog')).not.toBeVisible({ timeout: 15000 });
  await expect(page.locator('.terminal-pane:not([hidden])')).toContainText('boxhaven@background-box');
  assert.equal(JSON.parse(readFileSync(stateFile, 'utf8')).machines.length, 2);
  await page.getByRole('button', { name: 'Destroy box…', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Destroy box…', exact: true })).toBeEnabled();
  assert.equal(existsSync(`${stateFile}.destructions`), false, 'Cancel must not invoke the CLI');
  const prompt = await app.evaluate(() => global.desktopSmoke.confirmations.at(-1));
  assert.match(prompt.message, /background-box/);
  assert.match(prompt.detail, /permanently deletes.*files/);
  assert.equal(prompt.defaultId, 0); assert.equal(prompt.cancelId, 0);
  await assert.rejects(page.evaluate(() => window.boxhaven.destroy('--help', '')), /changed/);
  await assert.rejects(page.evaluate(() => window.boxhaven.destroy('background-box', 'stale identity')), /changed/);
  await app.evaluate(() => { global.desktopSmoke.response = 1; });
  state = JSON.parse(readFileSync(stateFile, 'utf8'));
  state.destroyError = 'Provider refused deletion.'; save();
  await page.getByRole('button', { name: 'Destroy box…', exact: true }).click();
  await expect(page.locator('#action-error')).toContainText('Provider refused deletion');
  await expect(page.locator('.box-row')).toHaveCount(2);
  await expect(page.locator('.terminal-pane:not([hidden])')).toContainText('boxhaven@background-box');
  await page.screenshot({ path: join(out, 'desktop-destroy-error.png') });
  delete state.destroyError; state.destroyDelay = 1200; save();
  await page.getByRole('button', { name: 'Destroy box…', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Destroying…', exact: true })).toBeDisabled();
  await expect(page.locator('.box-row')).toHaveCount(1);
  await expect(page.locator('#session-header')).toBeHidden();
  assert.deepEqual(JSON.parse(readFileSync(stateFile, 'utf8')).machines.map(box => box.name), ['my-next-idea']);
  assert.deepEqual(readFileSync(`${stateFile}.destructions`, 'utf8').trim().split('\n').map(JSON.parse), [['destroy', 'background-box', '--force'], ['destroy', 'background-box', '--force']]);
  // A same-name replacement while confirmation is open must not be destroyed.
  await page.getByRole('button', { name: 'my-next-idea, online', exact: true }).click();
  await app.evaluate(({ dialog }) => {
    dialog.showMessageBox = () => new Promise(resolve => { global.desktopSmoke.confirm = resolve; });
  });
  await page.getByRole('button', { name: 'Destroy box…', exact: true }).click();
  await expect.poll(() => app.evaluate(() => typeof global.desktopSmoke.confirm)).toBe('function');
  state = JSON.parse(readFileSync(stateFile, 'utf8'));
  state.machines[0].provider_id = 'replacement'; save();
  await app.evaluate(() => global.desktopSmoke.confirm({ response: 1 }));
  await expect(page.locator('#action-error')).toContainText('box has changed');
  assert.equal(readFileSync(`${stateFile}.destructions`, 'utf8').trim().split('\n').length, 2);
  assert.deepEqual(errors, []);
  console.log('Desktop smoke passed: terminal lifecycle, creation, preview opening/validation/errors, missing preview, destruction confirmation/cancel/failure/success, and stale target protection.');
} finally { if (app) await app.close(); rmSync(temp, { recursive: true, force: true }); }
