/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ConsoleRouteRouteImport } from './routes/_console/route'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleImagesRouteImport } from './routes/_console/images'
import { Route as ConsoleDeviceRouteImport } from './routes/_console/device'
import { Route as ConsoleTeamIndexRouteImport } from './routes/_console/team.index'
import { Route as ConsoleBillingIndexRouteImport } from './routes/_console/billing.index'
import { Route as ConsoleTeamTeamRouteImport } from './routes/_console/team.$team'
import { Route as ConsoleBoxesNameRouteImport } from './routes/_console/boxes.$name'
import { Route as ConsoleBillingTeamRouteImport } from './routes/_console/billing.$team'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleImagesRoute = ConsoleImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleDeviceRoute = ConsoleDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleTeamIndexRoute = ConsoleTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleBillingIndexRoute = ConsoleBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleTeamTeamRoute = ConsoleTeamTeamRouteImport.update({
  id: '/team/$team',
  path: '/team/$team',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleBoxesNameRoute = ConsoleBoxesNameRouteImport.update({
  id: '/boxes/$name',
  path: '/boxes/$name',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleBillingTeamRoute = ConsoleBillingTeamRouteImport.update({
  id: '/billing/$team',
  path: '/billing/$team',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/device': typeof ConsoleDeviceRoute
  '/images': typeof ConsoleImagesRoute
  '/billing/$team': typeof ConsoleBillingTeamRoute
  '/boxes/$name': typeof ConsoleBoxesNameRoute
  '/team/$team': typeof ConsoleTeamTeamRoute
  '/billing/': typeof ConsoleBillingIndexRoute
  '/team/': typeof ConsoleTeamIndexRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/device': typeof ConsoleDeviceRoute
  '/images': typeof ConsoleImagesRoute
  '/': typeof ConsoleIndexRoute
  '/billing/$team': typeof ConsoleBillingTeamRoute
  '/boxes/$name': typeof ConsoleBoxesNameRoute
  '/team/$team': typeof ConsoleTeamTeamRoute
  '/billing': typeof ConsoleBillingIndexRoute
  '/team': typeof ConsoleTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteRouteWithChildren
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_console/device': typeof ConsoleDeviceRoute
  '/_console/images': typeof ConsoleImagesRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/billing/$team': typeof ConsoleBillingTeamRoute
  '/_console/boxes/$name': typeof ConsoleBoxesNameRoute
  '/_console/team/$team': typeof ConsoleTeamTeamRoute
  '/_console/billing/': typeof ConsoleBillingIndexRoute
  '/_console/team/': typeof ConsoleTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/reset-password'
    | '/device'
    | '/images'
    | '/billing/$team'
    | '/boxes/$name'
    | '/team/$team'
    | '/billing/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/reset-password'
    | '/device'
    | '/images'
    | '/'
    | '/billing/$team'
    | '/boxes/$name'
    | '/team/$team'
    | '/billing'
    | '/team'
  id:
    | '__root__'
    | '/_console'
    | '/invite'
    | '/reset-password'
    | '/_console/device'
    | '/_console/images'
    | '/_console/'
    | '/_console/billing/$team'
    | '/_console/boxes/$name'
    | '/_console/team/$team'
    | '/_console/billing/'
    | '/_console/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  InviteRoute: typeof InviteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/images': {
      id: '/_console/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ConsoleImagesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/device': {
      id: '/_console/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof ConsoleDeviceRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/team/': {
      id: '/_console/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof ConsoleTeamIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/billing/': {
      id: '/_console/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof ConsoleBillingIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/team/$team': {
      id: '/_console/team/$team'
      path: '/team/$team'
      fullPath: '/team/$team'
      preLoaderRoute: typeof ConsoleTeamTeamRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/boxes/$name': {
      id: '/_console/boxes/$name'
      path: '/boxes/$name'
      fullPath: '/boxes/$name'
      preLoaderRoute: typeof ConsoleBoxesNameRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/billing/$team': {
      id: '/_console/billing/$team'
      path: '/billing/$team'
      fullPath: '/billing/$team'
      preLoaderRoute: typeof ConsoleBillingTeamRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleDeviceRoute: typeof ConsoleDeviceRoute
  ConsoleImagesRoute: typeof ConsoleImagesRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleBillingTeamRoute: typeof ConsoleBillingTeamRoute
  ConsoleBoxesNameRoute: typeof ConsoleBoxesNameRoute
  ConsoleTeamTeamRoute: typeof ConsoleTeamTeamRoute
  ConsoleBillingIndexRoute: typeof ConsoleBillingIndexRoute
  ConsoleTeamIndexRoute: typeof ConsoleTeamIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleDeviceRoute: ConsoleDeviceRoute,
  ConsoleImagesRoute: ConsoleImagesRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleBillingTeamRoute: ConsoleBillingTeamRoute,
  ConsoleBoxesNameRoute: ConsoleBoxesNameRoute,
  ConsoleTeamTeamRoute: ConsoleTeamTeamRoute,
  ConsoleBillingIndexRoute: ConsoleBillingIndexRoute,
  ConsoleTeamIndexRoute: ConsoleTeamIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  InviteRoute: InviteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
