package main

import (
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	boxHavenSSHConfigInclude = "Include ~/.boxhaven/ssh/config"
	boxHavenSSHConfigHeader  = "# Generated by BoxHaven. Run `bh ssh-config refresh` to update."
)

func runSSHConfig(args []string) error {
	if len(args) == 0 || args[0] == "-h" || args[0] == "--help" {
		printSSHConfigUsage()
		return errHelp
	}

	switch args[0] {
	case "install":
		if len(args) != 1 {
			return fmt.Errorf("unexpected bh ssh-config install args: %v", args[1:])
		}
		cfg, err := loadSetupDefaults()
		if err != nil {
			return err
		}
		machines, err := listRemoteBackendMachines(cfg)
		if err != nil {
			return err
		}
		if _, _, err := ensureBoxHavenSSHDeviceKey(); err != nil {
			return err
		}
		if err := writeBoxHavenSSHConfig(cfg, machines); err != nil {
			return err
		}
		if err := installBoxHavenSSHConfigInclude(); err != nil {
			return err
		}
		success("Installed direct SSH configuration for %d box(es)", len(sshConfigMachines(machines)))
		info("Connect with `ssh bh-<name>`; scp, rsync, and VS Code Remote SSH use the same aliases")
		return nil
	case "refresh":
		if len(args) != 1 {
			return fmt.Errorf("unexpected bh ssh-config refresh args: %v", args[1:])
		}
		installed, err := boxHavenSSHConfigInstalled()
		if err != nil {
			return err
		}
		if !installed {
			return fmt.Errorf("direct SSH configuration is not installed; run `bh ssh-config install`")
		}
		cfg, err := loadSetupDefaults()
		if err != nil {
			return err
		}
		machines, err := listRemoteBackendMachines(cfg)
		if err != nil {
			return err
		}
		if err := writeBoxHavenSSHConfig(cfg, machines); err != nil {
			return err
		}
		success("Refreshed direct SSH configuration for %d box(es)", len(sshConfigMachines(machines)))
		return nil
	case "uninstall":
		if len(args) != 1 {
			return fmt.Errorf("unexpected bh ssh-config uninstall args: %v", args[1:])
		}
		if err := uninstallBoxHavenSSHConfigInclude(); err != nil {
			return err
		}
		configPath, err := boxHavenSSHGeneratedConfigPath()
		if err != nil {
			return err
		}
		if err := os.Remove(configPath); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove generated SSH config: %w", err)
		}
		success("Uninstalled direct SSH configuration")
		return nil
	case "certificate":
		if len(args) != 2 {
			return fmt.Errorf("bh ssh-config certificate requires a box name")
		}
		name := strings.ToLower(strings.TrimSpace(args[1]))
		if err := validateRemoteName(name); err != nil {
			return err
		}
		cfg, err := loadSetupDefaults()
		if err != nil {
			return err
		}
		machine, _, err := getRemoteBackendMachine(cfg, name)
		if err != nil {
			return err
		}
		if err := requireRemoteMachineBootstrapped(machine); err != nil {
			return err
		}
		_, err = refreshBoxHavenSSHCertificate(cfg, &machine)
		return err
	default:
		return fmt.Errorf("unknown bh ssh-config command %q", args[0])
	}
}

func printSSHConfigUsage() {
	fmt.Fprintln(os.Stderr, "USAGE:")
	fmt.Fprintln(os.Stderr, "  bh ssh-config install")
	fmt.Fprintln(os.Stderr, "  bh ssh-config refresh")
	fmt.Fprintln(os.Stderr, "  bh ssh-config uninstall")
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "Installs managed `bh-<name>` OpenSSH aliases with transparent short-lived certificates.")
}

func refreshInstalledSSHConfigFromBackend(cfg Config) error {
	installed, err := boxHavenSSHConfigInstalled()
	if err != nil || !installed {
		return err
	}
	machines, err := listRemoteBackendMachines(cfg)
	if err != nil {
		return err
	}
	return writeBoxHavenSSHConfig(cfg, machines)
}

func refreshInstalledSSHConfig(cfg Config, machines []remoteMachine) error {
	installed, err := boxHavenSSHConfigInstalled()
	if err != nil || !installed {
		return err
	}
	return writeBoxHavenSSHConfig(cfg, machines)
}

func boxHavenSSHConfigInstalled() (bool, error) {
	path, err := userSSHConfigPath()
	if err != nil {
		return false, err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("read SSH config: %w", err)
	}
	return hasExactConfigLine(string(data), boxHavenSSHConfigInclude), nil
}

func installBoxHavenSSHConfigInclude() error {
	path, err := userSSHConfigPath()
	if err != nil {
		return err
	}
	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read SSH config: %w", err)
	}
	if hasExactConfigLine(string(data), boxHavenSSHConfigInclude) {
		return nil
	}
	mode := os.FileMode(0o600)
	if info, statErr := os.Stat(path); statErr == nil {
		mode = info.Mode().Perm()
	}
	contents := boxHavenSSHConfigInclude + "\n"
	if len(data) > 0 {
		contents += "\n" + string(data)
	}
	return atomicWriteFile(path, []byte(contents), mode)
}

func uninstallBoxHavenSSHConfigInclude() error {
	path, err := userSSHConfigPath()
	if err != nil {
		return err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read SSH config: %w", err)
	}
	lines := strings.Split(string(data), "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.TrimSpace(line) == boxHavenSSHConfigInclude {
			continue
		}
		kept = append(kept, line)
	}
	for len(kept) > 0 && strings.TrimSpace(kept[0]) == "" {
		kept = kept[1:]
	}
	mode := os.FileMode(0o600)
	if info, statErr := os.Stat(path); statErr == nil {
		mode = info.Mode().Perm()
	}
	return atomicWriteFile(path, []byte(strings.Join(kept, "\n")), mode)
}

func writeBoxHavenSSHConfig(cfg Config, machines []remoteMachine) error {
	if _, _, err := ensureBoxHavenSSHDeviceKey(); err != nil {
		return err
	}
	if _, err := remoteKnownHostsPath(); err != nil {
		return err
	}
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve bh executable for SSH config: %w", err)
	}
	configPath, err := boxHavenSSHGeneratedConfigPath()
	if err != nil {
		return err
	}
	contents := renderBoxHavenSSHConfig(sshConfigMachines(machines), executable, remoteBackendURL(cfg))
	return atomicWriteFile(configPath, []byte(contents), 0o600)
}

func sshConfigMachines(machines []remoteMachine) []remoteMachine {
	configured := make([]remoteMachine, 0, len(machines))
	for _, machine := range machines {
		if validateRemoteName(machine.Name) != nil || net.ParseIP(strings.TrimSpace(machine.PublicIPv4)) == nil || !machine.BootstrapComplete {
			continue
		}
		configured = append(configured, machine)
	}
	sort.Slice(configured, func(i, j int) bool { return configured[i].Name < configured[j].Name })
	return configured
}

func renderBoxHavenSSHConfig(machines []remoteMachine, executable string, backendURL string) string {
	var config strings.Builder
	config.WriteString(boxHavenSSHConfigHeader)
	config.WriteString("\n\n")
	for _, machine := range machines {
		alias := boxHavenSSHMachineAlias(machine.Name)
		certificatePath := "~/.boxhaven/ssh/certs/" + alias + "-cert.pub"
		refreshCommand := "env BOXHAVEN_BACKEND_URL=" + shellQuote(backendURL) + " " + shellQuote(executable) + " ssh-config certificate " + shellQuote(machine.Name) + " >/dev/null"
		fmt.Fprintf(&config, "Host %s\n", alias)
		fmt.Fprintf(&config, "    HostName %s\n", machine.PublicIPv4)
		fmt.Fprintf(&config, "    User %s\n", sshConfigUser(machine.SSHUser))
		fmt.Fprintln(&config, "    Port 22")
		fmt.Fprintln(&config, "    IdentityFile ~/.boxhaven/ssh/id_ed25519")
		fmt.Fprintf(&config, "    CertificateFile %s\n", certificatePath)
		fmt.Fprintln(&config, "    IdentitiesOnly yes")
		fmt.Fprintln(&config, "    PreferredAuthentications publickey")
		fmt.Fprintln(&config, "    PasswordAuthentication no")
		fmt.Fprintln(&config, "    KbdInteractiveAuthentication no")
		fmt.Fprintln(&config, "    NumberOfPasswordPrompts 0")
		fmt.Fprintln(&config, "    UserKnownHostsFile ~/.boxhaven/remote_known_hosts")
		fmt.Fprintln(&config, "    StrictHostKeyChecking accept-new")
		fmt.Fprintln(&config, "    CheckHostIP no")
		fmt.Fprintln(&config, "    HashKnownHosts no")
		fmt.Fprintf(&config, "    HostKeyAlias %s\n", machine.sshHostAlias())
		fmt.Fprintln(&config, "    ServerAliveInterval 30")
		fmt.Fprintf(&config, "Match originalhost %s exec %s\n", alias, sshConfigDoubleQuote(refreshCommand))
		fmt.Fprintln(&config, "    BatchMode yes")
		config.WriteString("\n")
	}
	return config.String()
}

func refreshBoxHavenSSHCertificate(cfg Config, machine *remoteMachine) (string, error) {
	privateKeyPath, publicKey, err := ensureBoxHavenSSHDeviceKey()
	if err != nil {
		return "", err
	}
	cert, err := getRemoteBackendSSHCertificate(cfg, machine.Name, publicKey)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(cert.Certificate) == "" {
		return "", fmt.Errorf("remote backend returned no SSH certificate for %s", machine.Name)
	}
	certificatePath, err := boxHavenSSHCertificatePath(machine.Name)
	if err != nil {
		return "", err
	}
	if err := atomicWriteFile(certificatePath, []byte(strings.TrimSpace(cert.Certificate)+"\n"), 0o600); err != nil {
		return "", fmt.Errorf("write BoxHaven SSH certificate: %w", err)
	}
	machine.SSHKeyPath = privateKeyPath
	machine.SSHCertificatePath = certificatePath
	machine.SSHHost = strings.TrimSpace(cert.Host)
	machine.SSHPort = cert.Port
	if strings.TrimSpace(cert.SSHUser) != "" {
		machine.SSHUser = strings.TrimSpace(cert.SSHUser)
	}
	return certificatePath, nil
}

func ensureBoxHavenSSHDeviceKey() (string, string, error) {
	if err := requireRemoteClientTools("ssh-keygen"); err != nil {
		return "", "", err
	}
	dir, err := boxHavenSSHDirectory()
	if err != nil {
		return "", "", err
	}
	if err := os.MkdirAll(filepath.Join(dir, "certs"), 0o700); err != nil {
		return "", "", fmt.Errorf("create BoxHaven SSH directory: %w", err)
	}
	if err := os.Chmod(dir, 0o700); err != nil {
		return "", "", fmt.Errorf("secure BoxHaven SSH directory: %w", err)
	}
	keyPath := filepath.Join(dir, "id_ed25519")
	publicKeyPath := keyPath + ".pub"
	if _, err := os.Stat(keyPath); errors.Is(err, os.ErrNotExist) {
		_ = os.Remove(publicKeyPath)
		command := exec.Command("ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "boxhaven-device", "-f", keyPath)
		if output, keyErr := command.CombinedOutput(); keyErr != nil {
			return "", "", fmt.Errorf("generate BoxHaven SSH key: %w: %s", keyErr, strings.TrimSpace(string(output)))
		}
	} else if err != nil {
		return "", "", fmt.Errorf("inspect BoxHaven SSH key: %w", err)
	}
	if err := os.Chmod(keyPath, 0o600); err != nil {
		return "", "", fmt.Errorf("secure BoxHaven SSH key: %w", err)
	}
	publicKey, err := os.ReadFile(publicKeyPath)
	if errors.Is(err, os.ErrNotExist) {
		command := exec.Command("ssh-keygen", "-y", "-f", keyPath)
		publicKey, err = command.Output()
		if err == nil {
			err = atomicWriteFile(publicKeyPath, append([]byte(strings.TrimSpace(string(publicKey))), '\n'), 0o644)
		}
	}
	if err != nil {
		return "", "", fmt.Errorf("read BoxHaven SSH public key: %w", err)
	}
	return keyPath, strings.TrimSpace(string(publicKey)), nil
}

func boxHavenSSHMachineAlias(name string) string {
	return "bh-" + strings.ToLower(strings.TrimSpace(name))
}

func sshConfigUser(user string) string {
	user = strings.TrimSpace(user)
	if user == "" {
		return remoteDefaultSSHUser
	}
	for index, character := range user {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || character == '_' || (index > 0 && character >= '0' && character <= '9') || (index > 0 && character == '-') {
			continue
		}
		return remoteDefaultSSHUser
	}
	return user
}

func boxHavenSSHCertificatePath(name string) (string, error) {
	if err := validateRemoteName(name); err != nil {
		return "", err
	}
	dir, err := boxHavenSSHDirectory()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "certs", boxHavenSSHMachineAlias(name)+"-cert.pub"), nil
}

func boxHavenSSHDirectory() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil || strings.TrimSpace(home) == "" {
		return "", fmt.Errorf("resolve home directory for BoxHaven SSH configuration")
	}
	return filepath.Join(home, ".boxhaven", "ssh"), nil
}

func boxHavenSSHGeneratedConfigPath() (string, error) {
	dir, err := boxHavenSSHDirectory()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "config"), nil
}

func userSSHConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil || strings.TrimSpace(home) == "" {
		return "", fmt.Errorf("resolve home directory for SSH configuration")
	}
	return filepath.Join(home, ".ssh", "config"), nil
}

func atomicWriteFile(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	temporary, err := os.CreateTemp(dir, ".boxhaven-write-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(data); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func hasExactConfigLine(contents string, target string) bool {
	for _, line := range strings.Split(contents, "\n") {
		if strings.TrimSpace(line) == target {
			return true
		}
	}
	return false
}

func sshConfigDoubleQuote(value string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`
}
