import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { StateStore } from "./state.js";
import { teamSnapshot } from "./team_sync.js";

test("sharing and operation records persist across restart, reset on team move, and never replay interrupted work", async t => {
  const dir = await mkdtemp(join(tmpdir(), "boxhaven-resource-control-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  let store = new StateStore(join(dir, "state.db"), "fake");
  t.after(() => store.close());
  await store.putMachine({ name: "work", user_id: "alice", org_id: "team-a", provider: "fake" });
  const machine = (await store.getMachine("alice", "work"))!;
  const id = machine.resource_id!;
  assert.equal(await store.setResourceSharing(id, "team-a", "alice", { team_id: "team-a", revision: 0, team_role: "operator", members: [] }), true);
  const operation = (await store.reserveResourceOperation(id, "team-a", "alice", "unique-request", "request-hash"))!;
  const before = teamSnapshot(store, "team-a").cursor;
  store.close();
  store = new StateStore(join(dir, "state.db"), "fake");
  assert.equal(store.resourceSharing(id).team_role, "operator");
  store.recoverResourceOperations();
  assert.equal(store.resourceOperations(id)[0].state, "unknown");
  assert.equal(store.resourceOperations(id)[0].error_code, "backend_restarted");
  assert.ok(teamSnapshot(store, "team-a").cursor > before);
  assert.equal(await store.reserveResourceOperation(id, "team-a", "alice", "unique-request", "request-hash"), undefined);
  await store.finishResourceOperation({ ...operation, state: "completed" });
  assert.equal(store.resourceOperations(id)[0].state, "unknown");
  await store.putMachine({ ...machine, org_id: "team-b" });
  assert.deepEqual(store.resourceSharing(id), { team_id: "team-b", revision: 0, team_role: "viewer", members: [] });
  assert.deepEqual(store.resourceOperations(id), []);
  assert.equal(await store.setResourceSharing(id, "team-a", "alice", { team_id: "team-a", revision: 0, team_role: "operator", members: [] }), false);
  assert.equal(await store.setResourceSharing(id, "team-b", "alice", { team_id: "team-a", revision: 0, team_role: "operator", members: [] }), false);
  const next = (await store.reserveResourceOperation(id, "team-b", "alice", "new-request", "new-hash"))!;
  await store.deleteMachine("alice", "work");
  await store.finishResourceOperation({ ...next, state: "completed" });
  assert.equal(store.resourceOperations(id).length, 0);
  assert.equal((store.db.prepare("SELECT COUNT(*) AS n FROM core_resource_audit").get() as { n: number }).n, 1);
});
