const tasks = [
  {name:'checkout-fix', label:'Fix the checkout bug', agent:'Claude Code', initials:'JT', image:'sprout', prompt:'Find and fix the checkout validation bug.', lines:['Reading checkout.ts and its tests…','Found a missing check for empty addresses.','Updating validation and adding a regression test.'], result:'A fix you can review.'},
  {name:'search-feature', label:'Build product search', agent:'Codex', initials:'MK', image:'glasses', prompt:'Add product search with filters and keyboard navigation.', lines:['Inspecting the product catalog…','Adding the search route and filter controls.','Starting the app for a browser check.'], result:'A feature you can try.'},
  {name:'homepage-idea', label:'Try a new homepage', agent:'Claude Code', initials:'DS', image:'antenna', prompt:'Explore a simpler homepage. Keep the preview running.', lines:['Reading the current page and design tokens…','Building a more focused hero and product section.','Keeping the preview server running.'], result:'An idea you can compare.'}
];
const option = document.body.dataset.concept;
const portrait = t => `<img class="portrait" src="assets/box-${t.image}.svg" alt="">`;
const initials = t => `<span class="initials ${t.image}" title="Example teammate">${t.initials}</span>`;
const actions = '<div class="actions"><a class="button primary" href="#start">Get started <span aria-hidden="true">↗</span></a><a class="text-link" href="#parallel">See how it works <span aria-hidden="true">↓</span></a></div>';
const header = `<div class="review-bar"><a href="index.html">← All directions</a><nav aria-label="Design directions"><a href="a.html" ${option==='a'?'aria-current="page"':''}>A · Product</a><a href="b.html" ${option==='b'?'aria-current="page"':''}>B · Request</a><a href="c.html" ${option==='c'?'aria-current="page"':''}>C · Tasks</a></nav><span>Website concept</span></div><header class="site-header wrap"><a href="index.html" class="brand"><img src="../../backend/app/src/assets/boxhaven-logo.png" alt="">BoxHaven</a><nav aria-label="Website"><a href="#parallel">How it works</a><a href="#hosting">Self-host</a><a href="https://docs.boxhaven.dev/">Docs</a><a href="https://app.boxhaven.dev/" class="sign-in">Sign in <span aria-hidden="true">↗</span></a></nav></header>`;
const chips = '<div class="quiet-proof"><span>Claude Code + Codex</span><span>Separate remote machines</span><span>Open source</span></div>';
const workspace = () => `<figure class="workspace-figure" id="demo"><div class="workspace"><div class="window-top"><span class="window-dots"><i></i><i></i><i></i></span><span>BoxHaven</span><span class="tiny">Example workspace</span></div><div class="workspace-body"><aside class="box-list"><div class="list-heading">Your boxes <span>3 online</span></div><div class="task-selectors" role="tablist" aria-label="Example remote boxes">${tasks.map((t,i)=>`<button id="task-${i}" role="tab" aria-selected="${i===0}" aria-controls="terminal" data-task="${i}">${portrait(t)}<span><strong>${t.name}</strong><small><i class="dot"></i> Online</small></span>${initials(t)}</button>`).join('')}</div><div class="list-foot">Each task has its own machine.</div></aside><section class="terminal-view"><div class="terminal-head"><div><strong id="terminal-name">checkout-fix</strong><span id="terminal-agent">Claude Code · Remote Linux</span></div><span class="preview-label">Open preview ↗</span></div><div class="terminal-content" id="terminal" role="tabpanel" aria-labelledby="task-0" tabindex="0"><p class="shell">~/project $ claude</p><p class="prompt">› ${tasks[0].prompt}</p><div class="terminal-lines">${tasks[0].lines.map(l=>`<p><span>●</span> ${l}</p>`).join('')}</div><span class="cursor"></span></div></section></div></div><figcaption>Switch between boxes. Each agent keeps running while you work elsewhere.</figcaption></figure>`;
const taskCards = () => `<div class="task-cards">${tasks.map(t=>`<article><div class="card-id">${portrait(t)}<span>${t.agent}</span>${initials(t)}</div><h3>${t.label}</h3><p>${t.prompt}</p><div class="card-bottom"><i class="dot"></i> Separate remote box <span>↗</span></div></article>`).join('')}</div>`;
const hosting = `<section class="hosting wrap" id="hosting"><div><span class="eyebrow">YOUR SETUP</span><h2>Start on our cloud.<br>Or run it on yours.</h2><p>The desktop app, backend, and CLI are open source. Use BoxHaven hosting, or self-host the backend and connect your own cloud account.</p></div><div class="hosting-options"><article><span class="small-symbol">☁</span><div><h3>BoxHaven Cloud</h3><p>Create boxes from the console and start working.</p><a href="https://app.boxhaven.dev/">Open console ↗</a></div></article><article><span class="small-symbol">⌘</span><div><h3>Self-hosted</h3><p>Run the control plane and boxes in infrastructure you manage.</p><a href="https://github.com/finbarr/boxhaven/tree/master/deploy/digitalocean">View the source ↗</a></div></article></div></section>`;
const start = `<section class="start wrap" id="start"><div><span class="eyebrow">GET STARTED</span><h2>Give your agent<br>more room to work.</h2><p>Install the BoxHaven skill, then ask Claude Code or Codex to run your independent tasks in separate boxes.</p><a class="text-link" href="https://docs.boxhaven.dev/getting-started">Setup guide ↗</a></div><div class="install-panel"><label for="install-command">Install the agent skill</label><div class="command"><code id="install-command">npx skills add finbarr/boxhaven --skill boxhaven -g -a codex claude-code</code><button class="copy" aria-label="Copy install command">Copy</button></div><details><summary>First-time setup</summary><p>Install and sign in to the bh CLI first. The skill requires Node.js 22.20+. After installation, open a new agent session and invoke <code>$boxhaven</code> in Codex or <code>/boxhaven</code> in Claude.</p></details><div class="install-links"><a href="https://docs.boxhaven.dev/desktop">Desktop app setup ↗</a><a href="https://github.com/finbarr/boxhaven">GitHub ↗</a></div></div></section>`;
const footer = `<footer class="wrap"><a class="brand" href="index.html"><img src="../../backend/app/src/assets/boxhaven-logo.png" alt="">BoxHaven</a><span>More work in motion.</span><a href="index.html">Back to design review ↑</a></footer>`;
let main;
if (option==='a') {
  main = `<section class="hero hero-a wrap"><span class="eyebrow">FOR CLAUDE CODE & CODEX</span><h1>Run your coding agents<br><em>in parallel.</em></h1><p class="lead">Give each task a remote machine.<br>Manage them all from one desktop app.</p>${actions}${workspace()}${chips}</section><section class="parallel wrap" id="parallel"><div class="section-heading"><div><span class="eyebrow">INDEPENDENT TASKS, RUNNING TOGETHER</span><h2>Keep more than<br>one thing moving.</h2></div><p>Fix a bug, build a feature, explore a new direction. Each agent gets its own files, tools, and compute.</p></div>${taskCards()}<div class="support-row"><article><span>01</span><h3>Stay in control</h3><p>Open any box’s terminal to check progress and steer the work.</p></article><article><span>02</span><h3>Share what’s running</h3><p>See your team’s boxes and share web previews with a link.</p></article><article><span>03</span><h3>Step away</h3><p>Remote sessions keep running after you close your laptop.</p></article></div></section>${hosting}${start}`;
} else if (option==='b') {
  main = `<section class="hero hero-b wrap"><div class="hero-copy"><span class="eyebrow">PARALLEL WORK, FROM A SINGLE REQUEST</span><h1>More ideas<br><em>in motion.</em></h1><p class="lead">Ask your coding agent to split independent work across remote boxes. Let several tasks move forward at once.</p>${actions}<p class="micro">Claude Code · Codex · Open source</p></div><div class="request-visual"><div class="example-label">EXAMPLE REQUEST</div><div class="request-card"><span class="prompt-mark">›</span><p>Use BoxHaven to try three homepage directions in separate boxes. Keep every preview running so I can compare them.</p><span class="prompt-caret">↵</span></div><div class="branch-lines" aria-hidden="true"><span></span><span></span><span></span></div><div class="idea-grid">${['Editorial','Product led','Minimal'].map((name,i)=>`<article class="idea-card"><div class="idea-heading">${portrait(tasks[i])}<span>${name}</span></div><div class="mini-site site-${i}"><div class="mini-nav"></div><div class="mini-title"></div><div class="mini-title short"></div><div class="mini-content"><i></i><i></i><i></i></div></div><span class="idea-foot"><i class="dot"></i> Own box · Own preview</span></article>`).join('')}</div><p class="visual-caption">Three independent agents. Three directions to compare.</p></div></section><section class="how-band" id="parallel"><div class="wrap"><div class="section-heading"><h2>You choose the work.<br>Your agent starts the boxes.</h2><p>Keep using the coding agent you already know. The BoxHaven skill handles the remote workflow.</p></div><div class="support-row"><article><span>01</span><h3>Describe the tasks</h3><p>Ask for independent work to run in parallel.</p></article><article><span>02</span><h3>Give each a workspace</h3><p>Each remote box gets its own project copy and compute.</p></article><article><span>03</span><h3>Check in when you want</h3><p>Open a terminal, inspect the work, or follow a preview.</p></article></div></div></section><section class="wrap workbench"><div class="section-heading"><h2>A place to see<br>what’s going on.</h2><p>The desktop app puts every remote box within reach.</p></div>${workspace()}</section>${hosting}${start}`;
} else {
  main = `<section class="hero hero-c wrap"><div class="hero-copy"><span class="eyebrow">YOUR CODING AGENTS, WORKING SIDE BY SIDE</span><h1>One task shouldn’t<br><em>hold up the rest.</em></h1><p class="lead">Run Claude Code and Codex on independent remote machines. Start the next task while the others keep going.</p>${actions}</div><div class="task-ledger"><div class="ledger-head"><span>ON YOUR PLATE</span><span>All running in parallel ↙</span></div>${tasks.map((t,i)=>`<article>${portrait(t)}<div><span class="task-number">0${i+1}</span><h3>${t.label}</h3><p>${t.agent} <span>·</span> ${t.name}</p></div><div class="ledger-state"><i class="dot"></i> Online</div></article>`).join('')}<div class="ledger-foot"><span>One box per task.</span><span class="mini-avatars">${tasks.map(initials).join('')}</span></div></div></section><section class="outcomes wrap" id="parallel"><div class="section-heading"><h2>What would you<br>put in parallel?</h2><div class="scenario-switch" role="group" aria-label="Example tasks"><button data-scenario="product" aria-pressed="true">Ship features</button><button data-scenario="explore" aria-pressed="false">Explore ideas</button><button data-scenario="maintain" aria-pressed="false">Clear a backlog</button></div></div><div id="scenario-cards">${taskCards()}</div></section><section class="workbench wrap"><div class="section-heading"><h2>Separate machines.<br>One place to check in.</h2><p>Keep each project independent. Open its terminal from the desktop app, or share its web preview with your team.</p></div>${workspace()}</section>${hosting}${start}`;
}
document.querySelector('#app').innerHTML = `${header}<main>${main}</main>${footer}`;
for (const button of document.querySelectorAll('[data-task]')) button.addEventListener('click',()=>{
  const task=tasks[Number(button.dataset.task)];
  document.querySelectorAll('[data-task]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));
  document.querySelector('#terminal-name').textContent=task.name;
  document.querySelector('#terminal-agent').textContent=`${task.agent} · Remote Linux`;
  document.querySelector('#terminal').setAttribute('aria-labelledby',button.id);
  document.querySelector('#terminal').innerHTML=`<p class="shell">~/project $ ${task.agent==='Codex'?'codex':'claude'}</p><p class="prompt">› ${task.prompt}</p><div class="terminal-lines">${task.lines.map(l=>`<p><span>●</span> ${l}</p>`).join('')}</div><span class="cursor"></span>`;
});
document.querySelector('.copy').addEventListener('click', async event=>{
  const button = event.currentTarget;
  try { await navigator.clipboard.writeText(document.querySelector('#install-command').textContent); button.textContent='Copied'; }
  catch { const range=document.createRange();range.selectNodeContents(document.querySelector('#install-command'));window.getSelection().removeAllRanges();window.getSelection().addRange(range);button.textContent='Select & copy'; }
});
const scenarioNames={product:['Fix the checkout bug','Build product search','Try a new homepage'],explore:['Try an editorial layout','Build a product-led page','Explore a minimal direction'],maintain:['Fix a flaky test','Update dependencies','Investigate a slow query']};
for(const button of document.querySelectorAll('[data-scenario]'))button.addEventListener('click',()=>{
 document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));
 const names=scenarioNames[button.dataset.scenario];
 document.querySelectorAll('#scenario-cards article').forEach((card,i)=>{card.querySelector('h3').textContent=names[i];card.querySelector('p').textContent=['Give this task its own project copy.','Keep its tools and dependencies separate.','Check the result when you’re ready.'][i];});
});
